M48
; DRILL file {KiCad 9.0.9} date 2026-08-02T19:51:57+0000
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-02T19:51:57+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.600
%
G90
G05
T1
X76.67Y-32.5
X76.67Y-35.5
X77.5Y-42.0
X77.5Y-51.0
X80.5Y-42.0
X80.5Y-51.0
T2
X3.0Y-3.0
X3.0Y-55.0
X70.0Y-55.0
X81.0Y-3.0
M30
